services:
  cliente-persona:
    build:
      context: ./ms-cliente-persona-api
      args:
        JAR_FILE: target/ms-cliente-persona-api-0.0.1-SNAPSHOT.jar
    container_name: cliente-persona
    ports:
      - "8080:8080"
    networks:
      - microservices-network
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/devTest
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  cuenta-movimientos:
    build:
      context: ./ms-cuenta-movimientos-api
      args:
        JAR_FILE: target/ms-cuenta-movimientos-api-0.0.1-SNAPSHOT.jar
    container_name: cuenta-movimientos
    ports:
      - "8081:8081"
    networks:
      - microservices-network
    depends_on:
      - postgres
      - cliente-persona
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/devTest
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=pass
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgres:
    image: postgres:13
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - microservices-network
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: devTest

networks:
  microservices-network:
    driver: bridge